action_redirection:
  users:
    html:
      create: show
      update: show
      destroy: index
      fallbacks:
        create: new
        update: edit
    turbo_stream:
      create: show
      update: show
      destroy: index
      fallbacks:
        create: new
        update: edit
        destroy: index

